# Generated by Django 4.1.7 on 2023-03-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datatable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("weight", models.FloatField(max_length=16)),
                ("sex", models.IntegerField()),
                ("race", models.IntegerField()),
                ("something_stolen", models.IntegerField()),
                ("unwanted_sex", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Headline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline_name", models.CharField(max_length=200)),
                ("headline_desc", models.CharField(max_length=200)),
                ("headline_content", models.CharField(max_length=1000)),
                (
                    "headline_image",
                    models.CharField(
                        default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbdpd2opUVxL2tYnU2Z2KlayBAbtfWUUuMYvu1_YpSUg&usqp=CAU&ec=48600113",
                        max_length=1000,
                    ),
                ),
            ],
        ),
    ]
