# Generated by Django 4.1.7 on 2023-03-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Datatable",),
    ]
